Repository pyne/pyne, pull requests merged in 2020-08, with the labels that each got.

#1256 Added Validation of LOOP through PWR measured data paper to publication list
  CHANGELOG.rst
  docs/pynepubs.bib
Labels: docs

#1258 Update contributing
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  CHANGELOG.rst
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
  PULL_REQUEST_TEMPLATE.md
Labels: docs

#1257 Issue1164
  CHANGELOG.rst
  pyne/data.pyx
Labels: bug, feature, in process

#1261 Ensdf pyne data
  CHANGELOG.rst
  pyne/dbgen/decay.py
Labels: data_repository

#1262 iPython --> Jupyter (Issue859)
  CHANGELOG.rst
  docs/devsguide/doc.rst
  docs/devsguide/testing.rst
  docs/gsoc/exp_data.rst
  docs/sphinxext/bibtex_sphinxext.py
  docs/theorymanual/decay.rst
  docs/usersguide/enrichment.rst
  tutorial/00-intro.ipynb
  tutorial/readme.rst
Labels: docs

#1264 An other attempt to fix nosetests on OSX-Conda
  CHANGELOG.rst
  src/h5wrap.h
  src/nucname.h
  src/particle.h
  src/rxname.h
  src/utils.h
Labels: build

#1267 Fix changelog
  CHANGELOG.rst
Labels: docs

#1265 change links to fendl data backup source
  CHANGELOG.rst
  pyne/dbgen/eaf.py
Labels: data_repository

#1273 Jupyter (formerly iPython) not needed in setup.py
  CHANGELOG.rst
  docs/devsguide/testing.rst
  docs/install/linux_source.rst
  readme.rst
  setup.py
Labels: bug, build, docs

#1263 (Docker) Install all Python packages with Pip
  CHANGELOG.rst
  docker/ubuntu_18.04-dev.dockerfile
  tests/travis-run-tests.sh
Labels: build

#1275 Typo in format string in pyne/fortranformat/_parser.py
  CHANGELOG.rst
  pyne/fortranformat/_parser.py
Labels: bug, low hanging pinoli

#1271 Python 2 to 3 Syntax for Tutorial and Example Jupyter Notebooks
  CHANGELOG.rst
  examples/ace.ipynb
  examples/chainsolve_transmutation.ipynb
  examples/data_sources.ipynb
  examples/discretized_teapot.ipynb
  examples/endf_reader.ipynb
  examples/fng_model.ipynb
  examples/half_life_plot.ipynb
  examples/material_library.ipynb
  examples/materials.ipynb
  examples/mesh_tags.ipynb
  examples/mstar_vs_flowrate.ipynb
  examples/origen22_h1_xs.ipynb
  examples/reaction_names.ipynb
  execer.py
  tests/test_tutorial_notebooks.py
  tutorial/00-intro.ipynb
  tutorial/01-nuclide-naming.ipynb
  tutorial/02-materials.ipynb
  tutorial/04-reaction_names.ipynb
  tutorial/05-cross-sections.ipynb
  tutorial/06-transmutation.ipynb
Labels: docs, low hanging pinoli, maintenance

#1279 Fix for half-life example
  CHANGELOG.rst
  examples/half_life_plot.ipynb
Labels: bug, docs

#1290 small changes to release instructions
  CHANGELOG.rst
  docs/devsguide/release.rst
Labels: docs

#1282 Low-hanging pinoli tutorial updates
  CHANGELOG.rst
  tutorial/00-intro.ipynb
  tutorial/01-nuclide-naming.ipynb
  tutorial/02-materials.ipynb
  tutorial/03-nuclear-data.ipynb
  tutorial/04-reaction_names.ipynb
  tutorial/06-transmutation.ipynb
  tutorial/09-outro.ipynb
Labels: docs, low hanging pinoli

#1284 Update chain solve transmutation and data sources examples
  CHANGELOG.rst
  examples/chainsolve_transmutation.ipynb
  examples/data_sources.ipynb
Labels: docs

#1280 Examples updates: material_library & material
  CHANGELOG.rst
  examples/material_library.ipynb
  examples/materials.ipynb
Labels: docs

#1287 Add the behaviorbot Welcome bot
  .github/config.yml
  CHANGELOG.rst
Labels: feature

#1285 Install Page Update
  CHANGELOG.rst
  docs/install/conda.rst
  docs/install/index.rst
  docs/install/supported.rst
  docs/install/ubuntu.rst
Labels: docs, low hanging pinoli

#1288 Re-ran mstar and reaction example notebooks; updated version mentions in readme
  CHANGELOG.rst
  examples/mstar_vs_flowrate.ipynb
  examples/reaction_names.ipynb
  readme.rst
Labels: docs, low hanging pinoli

#1293 Fix ace example
  CHANGELOG.rst
  examples/ace.ipynb
Labels: docs

#1295 Adding yt warning to examples notebooks
  CHANGELOG.rst
  examples/discretized_teapot.ipynb
  examples/fng_model.ipynb
  examples/mesh_tags.ipynb
Labels: bug, docs

#1296 Remove example Origen 2.2:H1 Cross Section
  CHANGELOG.rst
  docs/examples/index.rst
  docs/examples/origen22_h1_xs.rst
  docs/examples/origen22_h1_xs_thumb.png
Labels: docs

#1303 Add yt warning
  CHANGELOG.rst
  tutorial/07-mesh-basics.ipynb
Labels: docs

#1304 Updates to some of the last tutorials
  CHANGELOG.rst
  tutorial/00-intro.ipynb
  tutorial/05-cross-sections.ipynb
  tutorial/08-diffusion.ipynb
  tutorial/11-ensdf-processing.ipynb
Labels: docs

#1297 Update endf_reader.ipynb
  CHANGELOG.rst
  docs/tutorial/10.rst
  docs/tutorial/11.rst
  examples/endf_reader.ipynb
Labels: bug, docs

#1311 Fix various urls
  CHANGELOG.rst
  docs/dev_team.rst
  docs/theorymanual/data.rst
  docs/usersguide/jsoncpp.rst
  docs/usersguide/r2s.rst
  pyne/ace.pyx
  pyne/alara.py
  pyne/cccc.py
  pyne/rxname.pyx
  src/json-forwards.h
  src/json.h
  src/jsoncpp.cpp
Labels: docs

#1308 Ahot option
  CHANGELOG.rst
  CMakeLists.txt
  cmake/PyneMacros.cmake
  setup.py
Labels: build

#1317 Fixing endf_reader example's JSON
  CHANGELOG.rst
  examples/endf_reader.ipynb
Labels: docs

#1315 Taking over: Adds dependencies, making a PR, and updating documentation to NDG
  CHANGELOG.rst
  docs/devsguide/index.rst
  docs/devsguide/new_dev_guide.rst
  docs/devsguide/release.rst
  docs/devsguide/testing.rst
  docs/install/conda.rst
  docs/install/index.rst
  docs/install/linux_source.rst
  docs/install/osx.rst
  docs/install/source.rst
  docs/install/supported.rst
  docs/install/ubuntu.rst
Labels: build, docs

#1316 Update MCNP material reader to support default library identifier
  CHANGELOG.rst
  pyne/mcnp.py
  src/material.cpp
  tests/mcnp_inp.txt
  tests/test_mcnp.py
Labels: feature

#1307 Remove extra flag that prevented linking FORTRAN executables.
  CHANGELOG.rst
  cmake/PyneMacros.cmake
Labels: bug, build

#1298 Remove deprecated U mode in file open
  CHANGELOG.rst
  pyne/endf.pyx
  pyne/endl.py
Labels: bug, maintenance
